name: mobile
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  flutter: ">=3.0.0"
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  intl: ^0.20.2
  json_annotation: ^4.9.0
  http: ^1.5.0
  syncfusion_flutter_charts: ^32.1.22
  fl_chart: ^1.1.1

  cupertino_icons: ^1.0.8
  dio: ^5.9.0

  shared_preferences: ^2.2.2
  google_fonts: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_lint: ^3.0.3
  build_runner: ^2.4.11
  json_serializable: ^6.11.1

  flutter_lints: ^5.0.0
#  custom_lint: ^0.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/MoiPari.png
    - assets/images/mastercard.png
    - assets/images/contact_less.png
